### ISSUE TITLE
Accessing the application instance under ApplicationCommunicator

### ISSUE THREAD

**Issue by richtier** [django/asgiref#105]
Previously it was possible to access the application `instance` attached to an `ApplicationCommunicator` (useful during tests), but that changed here:

https://github.com/django/asgiref/commit/8ae25bd625b6da8b5f5cfe11e93bd33ea7bd456e#diff-bfbf47ad7bd80e4ba7e2340122c95a0dL17

That allows my tests check the instanciated application's properties.

Is there a new way to interact with the instantiated application?

**Comment by andrewgodwin** [comment]
There is not; I had never considered that to be a public interface, but I see that it makes sense if you have an application that is class-based.

If you want to send in a pull request to separate it into an assignment to `self.instance` and then the use of that assignment, I will happily take it.

**Comment by richtier** [comment]
smashing thanks

**Comment by richtier** [comment]
please see https://github.com/django/asgiref/pull/106

it's draft as I think my approach sucks, but so far it's the only way I get get the application instance exposed. Advice would be appreciated :)

My difficulty is `communicator.instance` is actually a corouting object rather than the application instance 
```
(Pdb) communicator.instance
<coroutine object WsgiToAsgi.__call__ at 0x7f23d59bdbf8>
```

**Comment by andrewgodwin** [comment]
Yeah, I just looked over there; I see what you tried to do to get around it, but it's not exactly pretty.

I think the key thing here is that because of the change to the single-callable style, there isn't an external way to get the instance any more - I forgot that, of course, you'd just get a coroutine if you pulled it out of the Future. There aren't really "instances" of applications any more in the high level sense, just closures as they're running.

It might be better to re-examine the basic problem - examining the application instance you're trying to test. What specifically do you need to talk in and out about?

**Comment by richtier** [comment]
Indeed, I felt dodgy writing it too 😆.

I have a Django channels websocket. On connect it creates an instance of an Alexa voice service client. On receive (of audio) the data is streamed to Alexa via the client.

It seems a better approach would be to mock the application class's `alexa_client` and perform assertions on the mock. I'll close the PR and this issue.

Thanks :)

**Comment by andrewgodwin** [comment]
No worries - thanks for bringing it up!
