### ISSUE TITLE
NamError: AttributeError not defined.

### ISSUE THREAD

**Issue by funaesthesia** [django/asgiref#157]
Django 3.0.5, Ubuntu 18.04, Python 3.8.0, mod_wsgi 4.7.1

```
[Sun May 03 17:26:52.817203 2020] [mpm_event:notice] [pid 2333:tid 140147783781312] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations 
[Sun May 03 17:26:52.817347 2020] [core:notice] [pid 2333:tid 140147783781312] AH00094: Command line: '/usr/sbin/apache2'
"/var/log/apache2/error.log" 50L, 4658C   
```

Djangoproject is working but templates won't change in real-time without a server restart. Then this error message shows up.

```
Exception ignored in: <function Local.__del__ at 0x7ff818ba5430>
Traceback (most recent call last):
  File "/var/www/my_app/.my_app_venv/lib/python3.8/site-packages/asgiref/local.py", line 95, in __del__
NameError: name 'AttributeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7ff818ba5430>
Traceback (most recent call last):  File "/var/www/my_app/.my_app_venv/lib/python3.8/site-packages/asgiref/local.py", line 95, in __del__
NameError: name 'AttributeError' is not defined 
```

VirtualHost setup
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerAdmin webmaster@localhost
	ServerName subdomain.example.com
	ServerAlias www.subdomain.example.com
	DocumentRoot /var/www/my_app
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

Include /etc/letsencrypt/options-ssl-apache.conf
... LE links

#Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"

Alias /media/ /var/www/my_app/media/
Alias /static/ /var/www/my_app/static/

<Directory /var/www/my_app/static>
Require all granted
</Directory>

<Directory /var/www/my_app/media>
Require all granted
</Directory>

<Directory /var/www/my_app>
	<Files wsgi.py>
		Require all granted
	</Files>
</Directory>

WSGIScriptAlias / /var/www/my_app/my_app/wsgi.py
WSGIDaemonProcess my_app python-home=/var/www/my_app/.my_app python-path=/var/www/my_app
WSGIProcessGroup my_app

</VirtualHost>
</IfModule>
```

Any suggestions? :) Thank you!

**Comment by andrewgodwin** [comment]
So, this line is troubling: `NameError: name 'AttributeError' is not defined`

`AttributeError` is a built-in object in every single Python version I can remember, including 3.8; if it's missing, then I'm afraid your Python installation is somehow deeply broken. Unfortunately I don't know quite _how_ it's broken - but that's the problem here, rather than an issue in asgiref.

It's possible the issue is just inside `mod_wsgi` - use a `python` shell in the terminal to check and see if just typing `AttributeError` works. That would help you narrow down if it's a problem just with `mod_wsgi` or with Python on your entire system.

**Comment by adamchainz** [comment]
I see a number of `AttributeError` + async fixes in recent Python 3.8.x changelog entries. Upgrading from 3.8.0 to 3.8.2 may include the fix.

https://docs.python.org/3/whatsnew/changelog.html

**Comment by funaesthesia** [comment]
> So, this line is troubling: `NameError: name 'AttributeError' is not defined`
> 
> `AttributeError` is a built-in object in every single Python version I can remember, including 3.8; if it's missing, then I'm afraid your Python installation is somehow deeply broken. Unfortunately I don't know quite _how_ it's broken - but that's the problem here, rather than an issue in asgiref.
> 
> It's possible the issue is just inside `mod_wsgi` - use a `python` shell in the terminal to check and see if just typing `AttributeError` works. That would help you narrow down if it's a problem just with `mod_wsgi` or with Python on your entire system.

Yes I noticed that too. What I did was a new install with Python 3.7.5 and compiling the wsgi not via the pip install mod-wsgi option but according to your documentation. It didn't give me the NameError warning in the standard shell so it was not a Python-specific problem. I guess it might have been something between the pip install mod_wsgi and the Python version. Who knows...

**Comment by funaesthesia** [comment]
I could reproduce it again today on a fresh install of Python 3.8.0 installed with apt. It seems as if it has got something to do with templates. The error pops up as soon as I set a TEMPLATES[{DIR = [os.path.join(BASE_DIR, 'templates')]. No AttributeError whatsoever up to that point.

**Comment by adamchainz** [comment]
Please upgrade to 3.8.2 as per my message.

**Comment by funaesthesia** [comment]
> Please upgrade to 3.8.2 as per my message.

I upgraded - made it even "worse" - now the error shows up independent of any django template dir. https://github.com/GrahamDumpleton/mod_wsgi/issues/568

**Comment by adamchainz** [comment]
Oh gosh! Well thank you for trying.

There might be something weird with Python's shutdown process running in an odd order and deleting `AttributeError` before deleting a `Local`. But that shouldn't normally happen.

I think mod_wsgi is less popular these days compared to, say, nginx + gunicorn.

I hope the mod_wsgi issue gets you some help. I'm sure Graham would find it useful if you could find a minimal reproducing case, perhaps a very basic WSGI app that uses a single `asgiref.Local()` object.

**Comment by GrahamDumpleton** [comment]
For the record, this is because the ``__del__()`` is triggering part way through the process of the Python interpreter being destroyed. As such, half the interpreter state is gone, including builtins. It can happen if a thread wakes up during shutdown for some reason, or even just in cleanup of objects on deletion of the interpreter. Since the process is being terminated anyway, it is usually of no consequence and can be ignored.

As to mod_wsgi being less popular, it is still better at least. ;-P

**Comment by adamchainz** [comment]
Thanks for the detalied explanation @GrahamDumpleton . It could be interesting to find out what the thread is, and maybe there is something asgiref should be doing about it.

> As to mod_wsgi being less popular, it is still better at least. ;-P

I did not dispute that 😅

**Comment by GrahamDumpleton** [comment]
Usually it is just a problem that can occur with daemon or externally created threads and can't do much about it. Arises in mod_wsgi sometimes since the request handler threads are all created outside of Python in C libraries of Apache and the threads just call into Python. So if one of those threads decides to wake up when the interpreter is being shutdown you can have a problem.

If this is specifically a daemon thread created to run ASGI, and that is using asyncio main loop and it is possible to shut it down, then one option might be to register an atexit callback which signals the event loop to shutdown somehow and then wait on a notification somehow that it is shutdown. So in effect you are waiting on the thread to finish before continue, like what Python usually does with non daemon threads, except here you could do whatever you need to to try and have the thread voluntarily shutdown.

Usually this sort of trick isn't possible as people don't write their daemon threads with an exit hatch so they can be stopped. Even if possible, probably not something you want to set up as a default. Could document how to do it though if becomes an issue, so people can try it.
