### ISSUE TITLE
Specification: Blacklisting an IP usecase

### ISSUE THREAD

**Issue by amirouche** [django/asgiref#174]
First, thanks for all the work, it is appreciated.

I am considering adapting ASGI to Scheme programming language but before I do that I wanted to make sure the specification can support all the cases I have in the mind. In particular the case of blacklisting a remote IP because of evil behavior at the application level. And ask the question about downstream -> upstream communication when nesting ASGI applications.

My understanding is that communication is ASGI `application(scope, receive, send)` goes through `scope` a read-only (?) dictionary and `receive` (toward downstream) and `send` (toward upstream) async callables.

While writing this issue, I think I figured the solution. I will explain anyway.

Imagine an application that considers the IP of the current `scope` and depending on the behavior of the associated user, decides to blacklist the user, hence the IP. So, the application would need to issue `send('http.disconnect')` ... and something like `send('http.blacklist')`.

The advantage of blacklisting an evil IP is that it will save some network and cpu. The server will not accept connections from that IP, hence no need to read and parse the HTTP request and wait until it reaches the application to disconnect it.

I think that approach works.

Feel free to close the issue if it is off-topic / resolved.

**Comment by andrewgodwin** [comment]
Yes, you could implement this with an ASGI middleware that could receive and intercept a special new message type (such as `http.block-ip`) and which then tracked the bad IPs in a datastore and if it saw one, immediately issued a `http.disconnect` rather than passing the connection down to the application.

However, I will caution that IP blocking should only be done as a temporary measure; most WAFs (Web Application Firewalls) do it via a timeout, since bad users can cycle out IPs pretty easily and leave someone unsuspecting with the now-blocked one.

**Comment by andrewgodwin** [comment]
(also, if you want to do this in a properly efficient manner, you'll end up wanting to do it at the kernel or network gear level, not at application level - but that's a whole different set of work!)
