### ISSUE TITLE
WSGI Error in non-ascii path

### ISSUE THREAD

**Issue by abersheeran** [django/asgiref#182]
https://github.com/encode/starlette/issues/997

I noticed that the ASGI document clearly states that utf8 encoding is required, but WSGI seems to require latin-1 encoding.

https://www.python.org/dev/peps/pep-3333/#a-note-on-string-types
https://asgi.readthedocs.io/en/latest/specs/www.html#connection-scope

**Comment by andrewgodwin** [comment]
Yup, that's correct - string encodings are pretty confusing in WSGI, which is why they are all set to utf-8 in ASGI. Anything that's translating between the two will have to do the right dance to re-encode them, and handle urlencoding as well.

I don't see a bug in ASGI here - if you have one, could you explain the exact bug in this package and what needs to be fixed it, and reopen? Thanks!

**Comment by abersheeran** [comment]
@andrewgodwin As mentioned above, the path encoding in ASGI is not consistent with the PATH_INFO encoding required by WSGI.

https://github.com/django/asgiref/blob/3020b4a309033ad0b7041dda7712b0ed729e338f/asgiref/wsgi.py#L59

I think it needs to be changed to the following code

```python
"PATH_INFO": scope["path"].encode("utf8").decode("latin1"), 
```

**Comment by andrewgodwin** [comment]
Oh, the bug is in _our_ WSGI adapter - sorry, I didn't realise that's what you meant!

Totally agree this should be fixed.
