### ISSUE TITLE
Best way to get the current loop with asgiref

### ISSUE THREAD

**Issue by pgjones** [django/asgiref#197]
I've been asked how to get the current event loop when on a thread created by asgiref i.e. why does `asyncio.get_event_loop()` error with `There is no current event loop in thread 'ThreadPoolExecutor-1_1'.`. I'm not sure what the right answer is/what is the best practice for this?

**Comment by andrewgodwin** [comment]
Well, that's because you're in a synchronous thread which, by its nature, has no event loop. If you want to somehow get the event loop on the main thread, you're going to either have to run thread on that loop to stash it, or rely on the internal, undocumented parts of `sync_to_async` that do this so that `async_to_sync` can then get back to it. That's currently `SyncToAsync.threadlocal.main_event_loop`, but again, please don't rely on that in production code; it's far less fragile to stash the loop you need yourself if you somehow need to schedule things on it.
