### ISSUE TITLE
wsgi question

### ISSUE THREAD

**Issue by euri10** [django/asgiref#265]
hi, I was in the process of trying to increase coverage on uvicorn and was in particular looking at those last 2 lines (93-94) (which are basically the same here, in uvicorn and hypercorn)

https://github.com/django/asgiref/blob/d1ee83f29dd25831e78ddd20f2bd0779e22b896e/asgiref/wsgi.py#L82-L94

no tests are hitting those last 2 lines, and I failed to find one that would.

It seems like dead code to me, but I may be missing something of course so I'd better ask before ignoring coverage on those, any ideas ?

**Comment by andrewgodwin** [comment]
Well, you're allowed to send headers more than once in the HTTP spec (https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), so those last two lines aggregate multiple header values in the scope (since ASGI says they should be kept separate - that's why `scope["headers"]` is a list not a dict) into a standardised form with commas between them, which is what WSGI expects.

We should probably add a test for this? It's really not hard to do so.

**Comment by euri10** [comment]
ha ! yeah, that makes suddenly more sense to me, thanks !

**Comment by euri10** [comment]
> We should probably add a test for this? It's really not hard to do so.

I just squeezed [one](https://github.com/encode/uvicorn/pull/1050) for uvicorn, can work on something similar should you want to

**Comment by andrewgodwin** [comment]
Yes please, if you want to drop that into a PR I'll happily improve our test coverage!
