### ISSUE TITLE
With 3.5.1 getting "RuntimeError: Single thread executor already being used, would deadlock"

### ISSUE THREAD

**Issue by LiteWait** [django/asgiref#323]
Tough time interpreting the commit comments, but running from my developer desktop with 3.5.1 I am still seeing (sporadically)...

"RuntimeError: Single thread executor already being used, would deadlock"

Python 3.9.1
uvicorn==0.15.0
uvloop==0.14.0
websockets==9.1
asgiref==3.5.1

**Comment by andrewgodwin** [comment]
Are you saying that this is a regression, and that everything is fine with 3.5.0?

**Comment by LiteWait** [comment]
I get the error on 3.4.1, 3.5.1. I'll test 3.5.0.  For now monkey patching thread_sensitive=False to get around it.

**Comment by LiteWait** [comment]
Same error on 3.5.0

**Comment by andrewgodwin** [comment]
You're running into the fix for https://github.com/django/asgiref/issues/249 - I suspect you are trying to call thread-sensitive sync_to_async (the default) twice in the same async task, which isn't possible to do because thread-sensitive mode always uses the same thread, and it would already be in use.

Fixes you can try:
- Turn off thread-sensitive mode by passing `thread_sensitive=False` to `sync_to_async`
- `await` the first sync_to_async call to ensure it's completed before doing the second one
