### ISSUE TITLE
ASGI should be callbacks-based to be more universal

### ISSUE THREAD

**Issue by pwtail** [django/asgiref#358]
I'm not sure what is the best place to discuss ASGI protocol. If this repo is OK, you probably can turn this issue into a Github Discussion.

ASGI is good at being a spec for an async server, but it can be more than that.

The spec would be more universal if it used a callback API, not coroutines and async/await. For example, instead of

```python
await send(message)
```

It could do this:

```python
send(message, cb=cb)
```

This way, websockets could be used for a WSGI app too, for example: at the end of the request handler, it could schedule sending a websocket message (just as an example).

**Comment by andrewgodwin** [comment]
This was considered during the early days of ASGI, but it was decided to make it a specifically async protocol; callbacks have a whole host of problems in terms of local variables and closures that we get to avoid by using native async support, and sync support is not really something we're after because there's good libraries for all of those already.

So, for that reason, I'm going to close this as "no, we won't do this". It wouldn't be ASGI; it would be something else.

**Comment by pwtail** [comment]
From what I see, it is used in callback-style by the servers anyway: creating a future and calling `future.set_result`

https://github.com/nginx/unit/blob/master/src/python/nxt_python_asgi_http.c
