### ISSUE TITLE
Provide the un-%-decoded path

### ISSUE THREAD

**Issue by edk0** [django/asgiref#51]
As far as I can tell, ASGI follows the precedent set by WSGI in providing only a %-decoded string representation of the path. I believe this is a mistake. In particular, `%2F` is not a path separator by the URI RFC, but an application can't tell it apart from `/`.

I suggest either providing a `raw_path` byte string, or deserializing the path properly and passing it as a list.

**Comment by andrewgodwin** [comment]
Unfortunately this is not possible at the moment, as the path is subject to re-interpretation by both reverse-proxying webservers and downstream proxies. I discussed this with a few other server maintainers before and everyone sadly agreed it had to be this way - if we provided a "raw" one then people might rely on it only for it to break later on when a webserver in front did exactly the same thing (webservers: not good at adhering perfectly to the URI RFC)

Given that, I don't think we can safely provide a raw path, and so I'm going to close this. Feel free to keep discussing though; my opinion is not set in stone, but I've revisited this particular topic several times over the last few years always with the same conclusion. There's a reason everything else is uninterpreted bytestrings where possible in ASGI apart from the path.

**Comment by CounterPillow** [comment]
I see the issue with downstream proxies since the website developers have no influence over these, but at least with reverse-proxies one could name the ones that do violate the RFC in this way in the documentation for such a `raw_path` string or alternative interface.

Right now ASGI is in the unfortunate position of throwing away information because servers further up the HTTP hot potato game would break assumptions made by devs about the validity of this information. This is very painful if a developer has confirmed their assumptions in the deployment they run, and determined that ASGI is the only place this information is being discarded.

**Comment by edk0** [comment]
I see where you're coming from. I haven't had time to exhaustively test reverse proxies, but I know that while, for example, nginx is (often) wrong by default, it can be configured to be right. ASGI can't.

Much as I understand the concern about people relying on a feature you can't guarantee will work, the alternative punishes people who do understand and control their stack, and serves to help lock in the incorrect behaviour.

Any feature like this would presumably need to be exposed to web app developers as a new feature in whatever framework, in order to avoid any security vulnerabilities, rather than silently upgrading URL fields to be able to contain a `/`. So there'd be ample opportunity for the new documentation that entails to have a big red warning saying "this won't work with all possible software configurations".

**Comment by andrewgodwin** [comment]
Yes, any addition like this would be a brand new addition to the HTTP scope for sure, and would be optional for servers to provide. It's very doable.

Of course, the balance to that is that even if it's possible, when you're talking about specifications you need more than "we can", you need a very strong "we should even though it partially duplicates existing data". ASGI, and WSGI before it, were never designed to give you perfect, low-level control over HTTP - if you want that, then there's plenty of Python HTTP server libraries you can write against. Instead, it's designed to solve something around the 95-99% case.

Given that, is distinguishing between `%2F` and `/` in URLs something that a considerable percentage of users are going to want? Years and years of this being in WSGI means that literally no Python programmer I've worked with has ever done this in the path (the query string is, of course, a separate matter, and that _does_ come raw).

The burden of proof on adding something like this in is, in my opinion, pretty large. There needs to be a good argument that it would benefit a lot of people and be worth duplicating data in a way that is potentially dangerous if the documentation isn't read properly.

**Comment by edk0** [comment]
> Yes, any addition like this would be a brand new addition to the HTTP scope for sure, and would be optional for servers to provide. It's very doable.

Of course. I meant to point out it'd also be a brand new addition to whichever ASGI framework a web developer is using; it wouldn't just magically start working with a software update. Any such hypothetical feature can and should make it obvious that not all server configurations can support it.

> Of course, the balance to that is that even if it's possible, when you're talking about specifications you need more than "we can", you need a very strong "we should even though it partially duplicates existing data". ASGI, and WSGI before it, were never designed to give you perfect, low-level control over HTTP

Right, but we're not quite talking about low-level control. ASGI throws away low-level details that are specified to be irrelevant, like casing in header names, and that's completely fine. That's not the case for paths, where there's a semantic distinction between `['foo', 'bar']` and `['foo/bar']`.

> Years and years of this being in WSGI means that literally no Python programmer I've worked with has ever done this in the path

> The burden of proof on adding something like this in is, in my opinion, pretty large.

I can't prove anything, of course, and if I understood why you considered this so dangerous, I'd probably agree with you. From my perspective, while the change wouldn't help a vast number of people, it wouldn't affect those people negatively either.

I can point out that uWSGI and Gunicorn both provide the raw Request-URI (as `REQUEST_URI` and `RAW_URI` respectively). Presumably this has come up when you've discussed it before. But my efforts to find out if they're significantly used have been inconclusive, and perhaps not even relevant since as non-standards they imply a specific choice of server and a willingness to break interoperability.

Anyway, I don't want to make a big deal of this. When I opened the issue thought I was raising an obvious omission. I'd still like to understand the reasons better, but if you really think adding this would cause more problems than it would solve, I can live with that.

**Comment by andrewgodwin** [comment]
I don't consider it dangerous, I just take a lot of convincing to add _anything_ to a spec, and to be honest it's equal parts academic reasoning and popular support. As you say, trying to find people who would conclusively use this is difficult.

**Comment by simonw** [comment]
It looks like I'm the case that needs this. I just filed a bug against uvicorn about this, and then found out about this existing discussion: https://github.com/encode/uvicorn/issues/261

My issue over there discusses my needs in detail - the short version is that I need to be able to tell the difference between the following two URLs:

* https://v0-25-2.datasette.io/fixtures-dd88475/table%2Fwith%2Fslashes.csv
* https://v0-25-2.datasette.io/fixtures-dd88475/table/with/slashes.csv

I would certainly appreciate the addition of a `raw_path` key.

**Comment by andrewgodwin** [comment]
@simonw How are you doing it on a WSGI server? There's no way to get a raw path via the WSGI spec that I know of, unless I missed something?

**Comment by simonw** [comment]
I'm currently using Sanic 0.7.0 which implements its own server on top of uvloop and https://github.com/MagicStack/httptools

As of Sanic 0.8.0 they have the same problem - I think thanks to this commit https://github.com/huge-success/sanic/commit/7303a06f83eb7db54f7718d29b9e45369d3cac5f - and the fact that my tests no longer worked with the upgraded version of Sanic was the trigger for me to finally push forward in porting away to Starlette/ASGI.

**Comment by simonw** [comment]
I'm genuinely the only person on earth who cares about the difference between `%2F` and `/` in a URL path, aren't I?

**Comment by simonw** [comment]
I'm scratching my head trying to come up with a change I can make to Datasette so I can cover this use-case while building on top of ASGI.

I need to support tables with slashes in the names because Datasette is supposed to work against any existing SQLite database, and / is a valid character in a sqlite table name.

Since I control the index page that links to the table pages, I can use an alternative encoding. A few options:

* /fixtures-dd88475/table?table=table/with/slashes (a special case that would only be used for tables with slashes in their names)
* /fixtures-dd88475/b64-dGFibGUvd2l0aC9zbGFzaGVz (base64 encoded name - again would only be used for / containing tables. I need to figure out what happens if a table name starts with b64- though)
* /fixtures-dd88475/tableU+002FwithU+002Fslashes

That last one isn't too terrible - and I can avoid it clashing with tables with the sequence U+002F in their names by encoding plus as U+002B

It's kind of frustrating to have to invent my own custom encoding scheme for this though, when URL encoding already exists!

**Comment by simonw** [comment]
I deployed a demo of that branch, here's what it looks like: https://datasette-encode-decode-table.now.sh/fixtures-43e2232/tableU+002FwithU+002Fslashes.csv

If it turns out the ASGI spec isn't ever going to support accessing the initial "raw" path object this looks like it will be a reasonable way forward for me.

**Comment by blueyed** [comment]
@simonw 
You are not alone! ;) => https://github.com/django/asgiref/issues/87

**Comment by ichorid** [comment]
@simonw , [you're not alone](https://github.com/Jermolene/TiddlyWiki5/discussions/5269#discussioncomment-211382) still!

**Comment by prabhakarjuzgar** [comment]
@simonw, you are not alone!!!

**Comment by davidism** [comment]
@andrewgodwin can you lock this? I don't think there's any more to be said here. If something new comes up, it can be discussed as a new issue.
