### ISSUE TITLE
Documenting ASGI.

### ISSUE THREAD

**Issue by tomchristie** [django/asgiref#58]
A few suggestions on how we might more prominently pitch ASGI as an independent interface, rather than leaning too heavily on it's Django-initiated heritage: 

* Configure the readthedocs URL as this repo's website in the GitHub interface.
* Have the first paragraph in the README be an ASGI preamble and link to the readthedocs site.
* Link Channels documentation to the readthedocs site, not the repo. Ensure that "ASGI" text in any documents is linked.
* Add [Edit on GitHub] links to https://asgi.readthedocs.io/en/latest/

Those are all small changes, that I think would make a bit of a difference to how it's presented.

Something bigger that could be considered:

* Move `asgiref` out of the django github org, and into an `asgiref` org.

I don't think that *necessarily* needs to be a big deal in terms of governance. It's only used for testing, (HttpCommunicator/WebSocketCommunicator) rather than part of the core stack. To go a step further those docs *could* get pushed into ASGI ref, and have the channels docs introduce and give examples of using them, but defer the full API docs to ASGI ref.

**Comment by andrewgodwin** [comment]
OK, so I've done the first four things, and in addition added an Implementation page since that seems useful (I added the first five things I thought of, let me know if there's more: https://asgi.readthedocs.io/en/latest/implementations.html).

That already makes it feel like more of a separate thing. Thanks for the nudge.

As for changing this to a new org, I think that probably has to happen at some point. Not sure how I feel about doing it yet? Hmm.

**Comment by tomchristie** [comment]
Good call on the “implementations” page.

Quart and API Star can go up on there too.

**Comment by andrewgodwin** [comment]
Added. I have put things with version numbers below 1.0 as beta - let me know if any of them are instead stable?
