### ISSUE TITLE
ThreadPool execution should preserve contextvar context.

### ISSUE THREAD

**Issue by tomchristie** [django/asgiref#71]
This is an implementation pattern, rather than something strictly for the ASGI spec.

Something that cropped up while implementing https://github.com/encode/sentry-asgi is that Python's ThreadPoolExecutor does not default to preserving the contextvars context, which *really* is what you want.

If you're using something like the Sentry SDK, then you needs `contextvars` in order to properly tie otherwise unrelated events together into, and you need it to continue working properly when threadpools are used.

Here's my fix in Starlette: https://github.com/encode/starlette/pull/192

Other ASGI tools and frameworks will want to use something similar when running sync code in threadpools.

Links to core issue here: https://github.com/encode/starlette/issues/191

**Comment by andrewgodwin** [comment]
Given that this is what `sync_to_async` does, are you suggesting we should apply it there? That's the only way Channels runs things in threadpools, I believe.

**Comment by airhorns** [comment]
FWIW we got bitten by this in our django-channels app and we're glad to see it fixed in the framework such that `ContextVar`s just work as you'd expect them across that thread boundary. We used https://pypi.org/project/contextvars-executor/ and a 

```python
loop = asyncio.get_event_loop()
loop.set_default_executor(ContextVarExecutor(max_workers=int(os.environ.get("ASGI_THREADS", 1))))
```
to fix this for anything using asyncio internally, but I think this fix means we can get rid of that. +1 for Python changing this sooner rather than later!
